# Generated by Django 4.1.3 on 2023-09-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=500, verbose_name='Role Name')),
            ],
            options={
                'verbose_name_plural': 'UserRole',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='UserCodes',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='User Codes'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='UserRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.userrole', verbose_name='User Role'),
        ),
    ]
