# Generated by Django 4.1.3 on 2023-09-18 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0002_userrole_myuser_usercodes_myuser_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountSystemName', models.CharField(max_length=500, verbose_name='Account System Name')),
            ],
            options={
                'verbose_name_plural': 'AccountSystem',
            },
        ),
        migrations.CreateModel(
            name='GridDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GridDimensionsName', models.CharField(max_length=500, verbose_name='Grid Dimensions')),
            ],
            options={
                'verbose_name_plural': 'GridDimensions',
            },
        ),
        migrations.CreateModel(
            name='SigninTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SigninTimeoutName', models.CharField(max_length=500, verbose_name='Signin Timeout Name')),
            ],
            options={
                'verbose_name_plural': 'SigninTimeout',
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateName', models.CharField(max_length=500, verbose_name='Rate Name')),
            ],
            options={
                'verbose_name_plural': 'VatRate',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='AddressLine1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='AddressLine2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ApprovedNeeded',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Approved Needed'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='PrintConfirmedOrderSlip',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Print Confirmed Order Slip'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='PrintOrderItems',
            field=models.BooleanField(blank=True, default='True', null=True, verbose_name='Print Order Items'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='StockClosingTime',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stock Closing Time'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='VatEnabled',
            field=models.BooleanField(blank=True, default='True', null=True, verbose_name='VAT Enabled'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='VatNo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='VAT No'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='AccountSystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.accountsystem', verbose_name='Account System'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='GridDimensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.griddimensions', verbose_name='Grid Dimensions'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='SigninTimeout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.signintimeout', verbose_name='Signin Timeout'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='VatRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.vatrate', verbose_name='VAT Rate'),
        ),
    ]
