# Generated by Django 4.1.3 on 2023-09-19 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0003_accountsystem_griddimensions_signintimeout_vatrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Business Unit',
            },
        ),
        migrations.CreateModel(
            name='HotelLocationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('BusinessUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelbusinessunit', verbose_name='Business Unit')),
            ],
            options={
                'verbose_name_plural': 'Hotel Location Code',
            },
        ),
    ]
