# Generated by Django 4.1.3 on 2023-09-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0004_hotelbusinessunit_hotellocationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcesId', models.CharField(max_length=500, verbose_name='Proces Id')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Process Config',
            },
        ),
        migrations.AlterField(
            model_name='hotelbusinessunit',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='hotellocationcode',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HotelStoreCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotellocationcode', verbose_name='Store Location')),
                ('Process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelprocessconfig', verbose_name='Process')),
            ],
            options={
                'verbose_name_plural': 'Hotel Store Code',
            },
        ),
        migrations.CreateModel(
            name='HotelStoreBinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreBinCode', models.CharField(max_length=500, verbose_name='Store Bin Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('CardNo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Card No')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('StoreCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelstorecode', verbose_name='Store Code')),
            ],
            options={
                'verbose_name_plural': 'Hotel Store Bin Code',
            },
        ),
    ]
